spring:
  application:
    name: jfsq-service
  zipkin:
    base-url: http://localhost:9000    
  sleuth:
    sampler:
    #收集比例
          percentage: 1.0
#  datasource:
#    url: jdbc:oracle:thin:@10.1.50.30:1521:orcl
#    username: system
#    password: oracledba
#    driver-class-name: oracle.jdbc.driver.OracleDriver

#jpa:  
#    hibernate:  
#      ddl-auto: update  
#    show-sql: true  

#mybatis:
#  config-location: classpath:mybatis-config.xml

server:
  port: 6100

eureka:
  client:
    serviceUrl:
      defaultZone: nonono
    healthcheck:
      enabled: true
  instance:
      prefer-ip-address: true   
